# Data Skills&Tricks

# 1pandas因子编写进阶操作

## 1.1透视表（pivot table）

数据汇总和分析工具   根据一个或多个列中的数据创建多维数据汇总表格
- 多维汇总
- 灵活 回测分析收益系列
- 聚合函数

In [21]:
#透视表
import pandas as pd
data = {
    'Salesperson':['Alice','Bob','Charlie','Alice','Bob','Charile'],
    'Category':['Electronics','Electronics','Electronics','Clothing','Clothing','Clothing'],
    'SalesAmount':[500,750,300,200,300,150]
}
df = pd.DataFrame(data)
df

  Salesperson     Category  SalesAmount
0       Alice  Electronics          500
1         Bob  Electronics          750
2     Charlie  Electronics          300
3       Alice     Clothing          200
4         Bob     Clothing          300
5     Charile     Clothing          150

In [22]:
#创建透视表，指定多个聚合函数
pivot_table = pd.pivot_table(df,values= 'SalesAmount',index='Salesperson',columns='Category',aggfunc=['sum','mean'])
pivot_table

                 sum                 mean
Category    Clothing Electronics Clothing Electronics
Salesperson
Alice          200.0       500.0    200.0       500.0
Bob            300.0       750.0    300.0       750.0
Charile        150.0         NaN    150.0         NaN
Charlie          NaN       300.0      NaN       300.0

## 1.2日期时间·数据操作

- 灵活的时间索引  支持 重采样 时间差 窗口操作         
- 例如 给了日频的 结果人家要一周的财报 就可以重采样 在重采样范围里做聚合操作 
- 例如10：31：42    10-31-42  或者10/31/42 转换字符串形式
- 例如没有补齐的 09/35/20   有时候吧09的0去掉  就不能用字符串了

- 时间序列操作 重采样 滑动窗口计算 移动平均值计算 时间差分析
- 日期 时间格式化和解析 s